[entryPoints]
  # HTTP entry point that redirects to HTTPS
  [entryPoints.web]
    address = ":80"

  # HTTPS entry point for secure traffic
  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]
      certResolver = "myresolver"
    [entryPoints.websecure.forwardedHeaders]
      trustedIPs = ["192.168.0.0/24", "173.245.48.0/20", "103.21.244.0/22", "103.22.200.0/22", "103.31.4.0/22", "141.101.64.0/18", "108.162.192.0/18", "190.93.240.0/20", "188.114.96.0/20", "197.234.240.0/22", "198.41.128.0/17", "162.158.0.0/15", "104.16.0.0/13", "104.24.0.0/14", "172.64.0.0/13"]
      insecure = false

  [entryPoints.internal]
    address = ":8080"

  [entryPoints.internalsecure]
    address = ":8443"
    [entryPoints.internalsecure.http.tls]
      certResolver = "internalresolver"
    [entryPoints.internalsecure.forwardedHeaders]
      trustedIPs = ["192.168.0.0/24"]
      insecure = false

[serversTransport]
  insecureSkipVerify = false

[certificateResolvers]
  [certificatesResolvers.myresolver.acme]   
    email = "B.j.wheeler484@gmail.com"
    storage = "acme.json"
    caServer = "https://acme-v02.api.letsencrypt.org/directory"
    [certificatesResolvers.myresolver.acme.dnsChallenge]
      provider = "cloudflare"
      resolvers = ["1.1.1.1:53", "8.8.8.8:53"]

  [certificatesResolvers.internalresolver.acme]
    email = "b.j.wheeler484@gmail.com"
    storage = "internal-acme.json"          
    caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
    [certificatesResolvers.internalresolver.acme.tlsChallenge]

[providers]
  [providers.file]   
    filename = "/dynamic-config.toml"
    watch = true              
  [providers.docker] 
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false

[api]
  dashboard = true
  insecure = true

[log]
  level = "DEBUG"           
  filePath = "/var/log/traefik/traefik.log"

[accessLog]
  filePath = "/var/log/traefik/access.log"
  bufferingSize = 100